# Generated by Django 5.1.4 on 2024-12-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate_url',
            field=models.FileField(blank=True, null=True, upload_to='PDF/'),
        ),
        migrations.AlterField(
            model_name='lessonvideo',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='lesson_video'),
        ),
    ]
