# Generated by Django 5.1.4 on 2024-12-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0004_alter_lessonvideo_video_coursematerial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='detail_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
